# 來源
# source: rtsp://user:password@ip:port/stream
source: /dev/video0
video_fps: 30

# 過濾相關
sample_per_second: 1
max_buff_frames: 10
mask_path: ./img/mask.png

# 偵測相關
motion_area_threshold: 3000

# 錄影相關, 如果x264太吃力, 就改回XVID
use_external_hd: true
select_partition_device: /dev/sdb1  # 1st 直接選取特定分割區並作為儲存的對象
path_out_external: /media/ex_hdd/  # 2nd 儲存到指定位置
path_out_local: ./recordings  # 3rd if not use or not detect external, then use this path as storage folder
rec_method: ffmpeg  # or opencv
rec_audio: false
# use_hwaccel: qsv  # 太舊了, 不需要
record_fps: 5
record_seconds: 10

# fourcc: x264
fourcc: XVID

# 是否show影像, 只適合一開始做測試
imshow: true


# 排程錄影
schedule:
  enabled: false
  start_time:
    hour: 5
    minute: 0
  end_time:
    hour: 19
    minute: 0
