# 來源
# source: rtsp://user:password@ip:port/stream
source: /dev/video0
video_fps: 30

# 過濾相關
sample_per_second: 2
max_buff_frames: 5
mask_path: ./img/mask.png

# 偵測相關
motion_area_threshold: 3000

# 錄影相關, 如果x264太吃力, 就改回XVID
use_external_hd: true
path_out_external: /media/ex_hdd/  # 1st 儲存到指定位置, 務必設定fstab
select_partition_device: /dev/sdb1  # 2nd 直接選取特定分割區並作為儲存的對象, 小心sdx會變
path_out_local: ./recordings  # 3rd if not use or not detect external, then use this path as storage folder
rec_method: ffmpeg  # or opencv
rec_audio: false
copy_stream: true
record_fps: 5  # copy_stream為false才會轉換特定fps
record_seconds: 60

# fourcc: x264
fourcc: XVID

# 是否show影像, 只適合一開始做測試
imshow: true
win_resolution: [600, 300]


# 排程錄影
schedule:
  enabled: false
  start_time:
    hour: 5
    minute: 0
  end_time:
    hour: 19
    minute: 0
